const	users = [
	{
		username:"Mrs. Susan",
		password:"pass",
		email:"english@yahoo.com",
		isTeacher:true
	},
	{
		username:"Mr. Nick",
		password:"pass",
		email:"science@yahoo.com",
		isTeacher:true
	},
	{
		username:"Mr. Bill",
		password:"pass",
		email:"history@yahoo.com",
		isTeacher:true
	},
	{
		username:"Mr. Guy",
		password:"pass",
		email:"math@yahoo.com",
		isTeacher:true
	},
	{
		username:"Mrs. Jen",
		password:"pass",
		email:"spanish@yahoo.com",
		isTeacher:true
	},
	{
		username:"Mrs. Bev",
		password:"pass",
		email:"art@yahoo.com",
		isTeacher:true
	},
	{
		username:"Mrs. Day",
		password:"pass",
		email:"music@yahoo.com",
		isTeacher:true
	},
	{
		username:"Randy",
		password:"pass",
		email:"parent1@yahoo.com",
		isTeacher:false
	},
	{
		username:"Arden",
		password:"pass",
		email:"parent2@yahoo.com",
		isTeacher:false
	},
	{
		username:"Hollis",
		password:"pass",
		email:"parent3@yahoo.com",
		isTeacher:false
	},
	{
		username:"Mickey",
		password:"pass",
		email:"parent4@yahoo.com",
		isTeacher:false
	},
	{
		username:"Whitney",
		password:"pass",
		email:"parent5@yahoo.com",
		isTeacher:false
	},
	{
		username:"Laverne",
		password:"pass",
		email:"parent6@yahoo.com",
		isTeacher:false
	},
	{
		username:"Sandy",
		password:"pass",
		email:"parent7@yahoo.com",
		isTeacher:false
	},
	{
		username:"Alex",
		password:"pass",
		email:"parent8@yahoo.com",
		isTeacher:false
	},
	{
		username:"Bob",
		password:"pass",
		email:"parent9@yahoo.com",
		isTeacher:false
	},
	{
		username:"Devon",
		password:"pass",
		email:"parent10@yahoo.com",
		isTeacher:false
	},
	{
		username:"Randal",
		password:"pass",
		email:"parent11@yahoo.com",
		isTeacher:false
	},
	{
		username:"Tessie",
		password:"pass",
		email:"parent12@yahoo.com",
		isTeacher:false
	},
	{
		username:"Mica",
		password:"pass",
		email:"parent13@yahoo.com",
		isTeacher:false
	},
	{
		username:"Elenora",
		password:"pass",
		email:"parent14@yahoo.com",
		isTeacher:false
	},
	{
		username:"Brook",
		password:"pass",
		email:"parent15@yahoo.com",
		isTeacher:false
	},
	{
		username:"Berny",
		password:"pass",
		email:"parent16@yahoo.com",
		isTeacher:false
	},
	{
		username:"Ashley",
		password:"pass",
		email:"parent17@yahoo.com",
		isTeacher:false
	},
	{
		username:"Cary",
		password:"pass",
		email:"parent18@yahoo.com",
		isTeacher:false
	},
	{
		username:"Jackie",
		password:"pass",
		email:"parent19@yahoo.com",
		isTeacher:false
	},
	{
		username:"Francis",
		password:"pass",
		email:"parent20@yahoo.com",
		isTeacher:false
	},
	{
		username:"Toby",
		password:"pass",
		email:"parent21@yahoo.com",
		isTeacher:false
	},
	{
		username:"Jamie",
		password:"pass",
		email:"parent22@yahoo.com",
		isTeacher:false
	},
	{
		username:"Garnett",
		password:"pass",
		email:"parent23@yahoo.com",
		isTeacher:false
	},
	{
		username:"Alexis",
		password:"pass",
		email:"parent24@yahoo.com",
		isTeacher:false
	},
	{
		username:"Flann",
		password:"pass",
		email:"parent25@yahoo.com",
		isTeacher:false
	},
	{
		username:"Carson",
		password:"pass",
		email:"parent26@yahoo.com",
		isTeacher:false
	},
	{
		username:"Ricki",
		password:"pass",
		email:"parent27@yahoo.com",
		isTeacher:false
	},
	{
		username:"Dell",
		password:"pass",
		email:"parent28@yahoo.com",
		isTeacher:false
	},
	{
		username:"Jules",
		password:"pass",
		email:"parent29@yahoo.com",
		isTeacher:false
	},
	{
		username:"Bryn",
		password:"pass",
		email:"parent30@yahoo.com",
		isTeacher:false
	},
	{
		username:"Shanon",
		password:"pass",
		email:"parent31@yahoo.com",
		isTeacher:false
	},
	{
		username:"Fran",
		password:"pass",
		email:"parent32@yahoo.com",
		isTeacher:false
	},
	{
		username:"Robin",
		password:"pass",
		email:"parent33@yahoo.com",
		isTeacher:false
	},
	{
		username:"Sandy",
		password:"pass",
		email:"parent34@yahoo.com",
		isTeacher:false
	},
	{
		username:"Dale",
		password:"pass",
		email:"parent35@yahoo.com",
		isTeacher:false
	},
	{
		username:"Sammie",
		password:"pass",
		email:"parent36@yahoo.com",
		isTeacher:false
	},
	{
		username:"Alpha",
		password:"pass",
		email:"parent37@yahoo.com",
		isTeacher:false
	},
	{
		username:"Aubrey",
		password:"pass",
		email:"parent38@yahoo.com",
		isTeacher:false
	},
	{
		username:"Peyton",
		password:"pass",
		email:"parent39@yahoo.com",
		isTeacher:false
	},
	{
		username:"Vic",
		password:"pass",
		email:"parent40@yahoo.com",
		isTeacher:false
	},
	{
		username:"Stevie",
		password:"pass",
		email:"parent41@yahoo.com",
		isTeacher:false
	},
	{
		username:"Odell",
		password:"pass",
		email:"parent42@yahoo.com",
		isTeacher:false
	},
	{
		username:"Keelan",
		password:"pass",
		email:"parent43@yahoo.com",
		isTeacher:false
	},
	{
		username:"Mies",
		password:"pass",
		email:"parent44@yahoo.com",
		isTeacher:false
	},
	{
		username:"Lesley",
		password:"pass",
		email:"parent45@yahoo.com",
		isTeacher:false
	},
	{
		username:"Marijn",
		password:"pass",
		email:"parent46@yahoo.com",
		isTeacher:false
	},
	{
		username:"Esme",
		password:"pass",
		email:"parent47@yahoo.com",
		isTeacher:false
	},
	{
		username:"Meredith",
		password:"pass",
		email:"parent48@yahoo.com",
		isTeacher:false
	},
	{
		username:"Cleo",
		password:"pass",
		email:"parent49@yahoo.com",
		isTeacher:false
	},
	{
		username:"Lauren",
		password:"pass",
		email:"parent50@yahoo.com",
		isTeacher:false
	},
	{
		username:"Celestine",
		password:"pass",
		email:"parent51@yahoo.com",
		isTeacher:false
	},
	{
		username:"Carol",
		password:"pass",
		email:"parent52@yahoo.com",
		isTeacher:false
	},
	{
		username:"Ariel",
		password:"pass",
		email:"parent53@yahoo.com",
		isTeacher:false
	},
	{
		username:"Frankie",
		password:"pass",
		email:"parent54@yahoo.com",
		isTeacher:false
	},
	{
		username:"Addison",
		password:"pass",
		email:"parent55@yahoo.com",
		isTeacher:false
	},
	{
		username:"Kelsey",
		password:"pass",
		email:"parent56@yahoo.com",
		isTeacher:false
	},
	{
		username:"Freddie",
		password:"pass",
		email:"parent57@yahoo.com",
		isTeacher:false
	},
	{
		username:"Kenzie",
		password:"pass",
		email:"parent58@yahoo.com",
		isTeacher:false
	},
	{
		username:"Dana",
		password:"pass",
		email:"parent59@yahoo.com",
		isTeacher:false
	},
	{
		username:"Beverly",
		password:"pass",
		email:"parent60@yahoo.com",
		isTeacher:false
	}
];
	

module.exports = users;	